# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='systemstate.State'),
        ),
    ]
