# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systemstate', '0002_auto_20170213_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('any', 'Any'), ('all', 'All')], max_length=3)),
                ('nested_conditions', models.ManyToManyField(blank=True, null=True, related_name='_condition_nested_conditions_+', to='systemstate.Condition')),
                ('states', models.ManyToManyField(blank=True, null=True, related_name='_condition_states_+', to='systemstate.State')),
            ],
        ),
        migrations.CreateModel(
            name='IrsendConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='command',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='systemstate.Condition'),
        ),
        migrations.AddField(
            model_name='device',
            name='irsend_config',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systemstate.IrsendConfig'),
        ),
    ]
