# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemstate', '0002_auto_20170218_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='name',
            field=models.CharField(default='<Unnamed Condition>', max_length=255),
            preserve_default=False,
        ),
    ]
